name: Auto Report Workflow

on:
  schedule:
    - cron: "0 8 * * *"  # Runs at 8:00 UTC, which is 9:00 German time
  workflow_dispatch:       # Manually trigger from GitHub UI or API

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          CDP_USER_KEY: ${{ secrets.CDP_USER_KEY }}
          CDP_USER_SECRET: ${{ secrets.CDP_USER_SECRET }}
          CDP_BUSINESS_UNIT: ${{ secrets.CDP_BUSINESS_UNIT }}
          CDP_VIEW: ${{ secrets.CDP_VIEW }}
          OFFICE365_EMAIL: ${{ secrets.OFFICE365_EMAIL }}
          OFFICE365_PASSWORD: ${{ secrets.OFFICE365_PASSWORD }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: |
          python auto-report/main.py
